# Generated by Django 2.2.3 on 2019-07-31 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_sport', models.CharField(max_length=250, verbose_name='type de sport')),
                ('statut', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descript_match', models.CharField(max_length=250, verbose_name='X face à Y')),
                ('equipe1', models.CharField(max_length=100)),
                ('equipe2', models.CharField(max_length=100)),
                ('vote1', models.IntegerField(default=0)),
                ('vote2', models.IntegerField(default=0)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_exp', models.DateTimeField(auto_now=True)),
                ('statut', models.BooleanField(default=True)),
                ('sport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sport_match', to='myapp.Sports')),
            ],
        ),
    ]
